"""Ajout de la colonne is_admin aux utilisateurs

Revision ID: 5982bc197731
Revises: 
Create Date: 2026-04-22 00:39:27.580163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5982bc197731'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_number'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_transaction_timestamp'))
        batch_op.create_unique_constraint(None, ['reference'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_user_email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_email'), ['email'], unique=False)
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_transaction_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_account_number'), ['account_number'], unique=False)

    # ### end Alembic commands ###
